#!/bin/bash

set -e

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TIME=$( date +"%z %F %T" )

if [ -z "$EMACS_CHINA_USER" ] || [ -z "$EMACS_CHINA_USER_API_KEY" ]; then
    echo "Will not be able to push to Github"
    echo
    echo "Because EMACS_CHINA_USER and/or EMACS_CHINA_USER_API_KEY is not set"
    exit 1
fi

cd $( dirname $0 )

printf "Update from ${TIME} ---\n"

git fetch origin

git checkout master
git pull origin master

git checkout commit-for-travis-ci
git pull origin commit-for-travis-ci
git rebase master

printf "${TIME}\n" >> rebuild.log

git add rebuild.log
git -c user.name='vps' -c user.email='vps' commit -m "Rebuild start at ${TIME}"

git push -f https://$EMACS_CHINA_USER:$EMACS_CHINA_USER_API_KEY@github.com/emacs-china/elpa commit-for-travis-ci

git fetch origin

printf "---\n\n"
