#!/bin/bash

set -e

export elpa="${elpa:=gnu}"

mkdir -p $elpa

emacs -Q --batch -l extract-package-url.el > "$elpa"-urls

cd $elpa

aria2c --check-certificate=false -i ../"$elpa"-urls || [ "$?" = "3" ]

cd ..
