#!/bin/bash

set -e

export elpa="${elpa:=gnu}"

mkdir -p $elpa

emacs -Q --batch -l extract-package-url.el > "$elpa"-urls

cd $elpa

aria2c --ca-certificate=/etc/ssl/certs/ca-certificates.crt -i ../"$elpa"-urls || [ "$?" = "3" ]

cd ..
