#!/bin/bash

set -e

echo ">>> Syncing MELPA <$( date +"%Y-%m-%d %H:%M:%S %Z" )>..."

rsync -avz --delete rsync://melpa.org/packages/ /var/elpa-packages/melpa
rsync -av --delete /var/elpa-packages/melpa/ /var/elpa/melpa
# Looks like the upstream doesn't have readable perm bit set for some files
chmod -R a+r /var/elpa/melpa

echo ">>> Done <$( date +"%Y-%m-%d %H:%M:%S %Z" )>"
